name: Flatpak Manifest
on:
  schedule:
    - cron: '0 0 * * 1' # run weekly
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab

jobs:
  flatpak-external-data-checker:
    name: Check for updates
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update manifest
        uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_COMMITTER_NAME: github-actions[bot]
          # email sets "github-actions[bot]" as commit author, see https://github.com/orgs/community/discussions/26560
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --update --never-fork build-aux/io.github.pantheon_tweaks.pantheon-tweaks.yml
