name: Gettext

on:
  # This workflow isn't scheduled because strings may be changed during development
  # so updating translation files may cause unnecessary translation work
  workflow_dispatch: {}

jobs:
  gettext:
    name: Gettext
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-50
      options: --privileged

    steps:
    - name: Install python3-git
      run: |
        pip3 install GitPython

    - name: Clone repository
      uses: actions/checkout@v6
      with:
        token: ${{ secrets.GIT_USER_TOKEN }}

    - name: Configure Git
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Update Translation Files
      uses: elementary/actions/gettext-flatpak@main
      with:
        manifest-path: io.github.pantheon_tweaks.pantheon-tweaks.yml
        repository-url: 'https://flathub.org/repo/flathub.flatpakrepo'
        repository-name: 'flathub'
      env:
        GIT_USER_NAME: "github-actions[bot]"
        GIT_USER_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
